### ISSUE TITLE
Latest version is 4.4.1

### ISSUE THREAD

**Issue by foxi69** [vot/ffbinaries-api#15]
Why is 4.4.1 the latest according to the api?

[https://ffbinaries.com/api/v1/version/latest](https://ffbinaries.com/api/v1/version/latest)

**Comment by vot** [comment]
Hi @foxi69,

It was a deliberate choice to hold the default version back for about a month.
Since we've been at 4.4.1 for literally two years and I published the newer versions of ffmpeg during the holidays I wanted to give people some time to test and avoid a potential avalanche of failed builds.

Apologies this wasn't communicated very well at the time (I only mentioned this plan in [a comment on an issue in ffbinaries-prebuilt repo](https://github.com/ffbinaries/ffbinaries-prebuilt/issues/17#issuecomment-1870888167)).
Since it's been just over a month now and there haven't been any complaints the "latest" version has been updated to 6.1 and a notice about that has been added on ffbinaries.com :)
